import React from 'react'
import Head from 'next/head'
import { SessionProvider } from 'next-auth/react'
import '../styles/globals.css'
import { Provider } from '../context'
import '@rainbow-me/rainbowkit/styles.css'
import { getDefaultWallets, RainbowKitProvider } from '@rainbow-me/rainbowkit'
import { chain, configureChains, createClient, WagmiConfig } from 'wagmi'
import { alchemyProvider } from 'wagmi/providers/alchemy'
import { publicProvider } from 'wagmi/providers/public'
import { AppProps } from 'next/app'

const { chains, provider } = configureChains(
  [chain.mainnet, chain.polygon, chain.optimism, chain.arbitrum],
  [alchemyProvider({ apiKey: process.env.ALCHEMY_ID ?? '' }), publicProvider()]
)
const { connectors } = getDefaultWallets({
  appName: 'My RainbowKit App',
  chains
})

const wagmiClient = createClient({
  autoConnect: true,
  connectors,
  provider
})

export const MyApp = ({ Component, pageProps }: AppProps) => {
  return (
    <WagmiConfig client={wagmiClient}>
      <RainbowKitProvider chains={chains}>
        <SessionProvider session={pageProps.session}>
          <Provider>
            <>
              <Head>
                <title>BeTrusty</title>
                <meta name='description' content='Generated by create-t3-app' />
                <link rel='icon' href='/favicon.ico' />
              </Head>
              <Component {...pageProps} />
            </>
          </Provider>
        </SessionProvider>
      </RainbowKitProvider>
    </WagmiConfig>
  )
}
